version: "3.7"

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - net_admin
    volumes:
      - ./tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    env_file:
      - .env
    restart: unless-stopped

  rustdesk-hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    network_mode: service:tailscale
    # ports:
    #   - "21115:21115"
    #   - "21116:21116"
    #   - "21118:21118"
    command: hbbs -r 0.0.0.0:21117
    depends_on:
      - tailscale
    restart: unless-stopped

  rustdesk-hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    network_mode: service:tailscale
    # ports:
    #   - "21117:21117"
    command: hbbr
    depends_on:
      - tailscale
    restart: unless-stopped
